"""Turn campaign JSON into the LaTeX tables of the experiments section.

Every emitted table carries, in a LaTeX comment above it, the JSON file, the
git SHA and the SLURM job id that produced its numbers -- so a reader of the
.tex source can trace any printed value back to the run, per the project rule
that no number enters a durable artifact without its provenance.

Usage:
    uv run --python 3.12 python make_tables.py --results <dir> --out <dir>
"""
import argparse
import json
import os
import statistics as st
from collections import defaultdict

FAMILY_LABEL = {
    "near_tree": "near tree", "sparse_er": "sparse ER", "grid": "grid",
    "geometric": "geometric", "small_world": "small world",
    "dense_er": "dense ER",
}

# Typeset forms of the ablation rungs.  adaptive.py's ASCII labels are for
# terminal output and contain characters LaTeX would choke on (gamma_0).
ABLATION_TEX = {
    "A0": "all roots, no truncation, no seed",
    "A1": "$+$ radius-$\\gamma/2$ truncation",
    "A2": "$+$ fundamental-cycle seed $\\gamma_0$",
    "A3": "$+$ $2$-core peeling",
    "A4": "$+$ block decomposition",
    "A5": "$+$ transversal roots",
    "A6": "$+$ greedy vertex-cover transversal",
    "A7": "$+$ adaptive $\\mu/n$ switch",
}


def load(results, name):
    p = os.path.join(results, name)
    return json.load(open(p)) if os.path.exists(p) else None


def prov_comment(d, fname):
    p = d.get("provenance", {})
    return (f"% generated by make_tables.py from {fname}\n"
            f"% git {p.get('git_sha','?')[:12]} dirty={p.get('git_dirty')} "
            f"job={p.get('slurm_job_id')} task={p.get('slurm_array_task_id')}\n"
            f"% host={p.get('host')} cpu={p.get('cpu')}\n")


# ------------------------------------------------------------------ runtime
def _iqr(xs):
    """Median and interquartile range, on the nearest-rank convention."""
    xs = sorted(xs)
    n = len(xs)
    if n == 1:
        return xs[0], xs[0], xs[0]
    med = st.median(xs)
    lo = xs[max(0, int(round(0.25 * (n - 1))))]
    hi = xs[min(n - 1, int(round(0.75 * (n - 1))))]
    return med, lo, hi


def table_runtime_spread(d, n_target=1600):
    """Median and IQR over independent draws per family."""
    by = defaultdict(list)
    for r in d["rows"]:
        if r["n"] == n_target:
            by[r["family"]].append(r)
    order = ["near_tree", "sparse_er", "small_world", "grid", "geometric", "dense_er"]
    fams = sorted(by, key=lambda f: order.index(f) if f in order else 99)
    n_inst = max(len(v) for v in by.values())
    out = [prov_comment(d, "timing.json")]
    out.append(r"""\begin{table}[ht]
\centering
\small
\begin{tabular}{|l|r|r|r|r|r|}
\hline
\textbf{Family} & $\mu/n$ & \textbf{all roots (s)} & \textbf{transversal (s)} & \textbf{adaptive (s)} & \textbf{adaptive vs.\ best fixed} \\ \hline""")
    for f in fams:
        rs = by[f]
        mu = st.median(r["mu_over_n"] for r in rs)
        cells = []
        for key in ("t_allroots", "t_transversal", "t_adaptive"):
            med, lo, hi = _iqr([r[key] for r in rs])
            cells.append(f"{med:.4f} \\tiny[{lo:.4f},{hi:.4f}]")
        rel = _iqr([min(r["t_allroots"], r["t_transversal"]) / r["t_adaptive"]
                    for r in rs])
        out.append(f"{FAMILY_LABEL.get(f, f):<14} & {mu:.3f} & " + " & ".join(cells) +
                   f" & {rel[0]:.2f}$\\times$ \\tiny[{rel[1]:.2f},{rel[2]:.2f}] \\\\ \\hline")
    out.append(r"""\end{tabular}
\caption{Exact-mode runtime at $n=""" + f"{n_target}" + r"""$ over $""" + f"{n_inst}" +
        r"""$ independent draws per family: median, with the interquartile range in
brackets. Best of five timed runs per draw, one core of an Intel Xeon Gold 6248,
Python 3.12. The final column compares the adaptive variant against whichever
\emph{fixed} strategy is better on that draw, so a value near $1$ means the
switch chose correctly and a spread straddling $1$ means the two are tied.}
\label{tab:runtime}
\end{table}""")
    return "\n".join(out)


def table_runtime(d, n_target=1600):
    if d.get("instances", 1) > 1:
        return table_runtime_spread(d, n_target)
    rows = [r for r in d["rows"] if r["n"] == n_target]
    order = ["near_tree", "sparse_er", "small_world", "grid", "geometric", "dense_er"]
    rows.sort(key=lambda r: order.index(r["family"]) if r["family"] in order else 99)
    out = [prov_comment(d, "timing.json")]
    out.append(r"""\begin{table}[ht]
\centering
\small
\begin{tabular}{|l|r|r|r|r|r|r|r|}
\hline
\textbf{Family} & $m$ & $\mu/n$ & \textbf{root cut} & \textbf{all roots (s)} & \textbf{transversal (s)} & \textbf{adaptive (s)} & \textbf{adaptive vs.\ best fixed} \\ \hline""")
    for r in rows:
        cut = 1 - r["roots_transversal"] / r["roots_allroots"]
        best_fixed = min(r["t_allroots"], r["t_transversal"])
        rel = best_fixed / r["t_adaptive"]
        # NB: the percent sign must be escaped -- an unescaped % comments out
        # the rest of the line, including the row terminator, and silently
        # merges two table rows.
        out.append(
            f"{FAMILY_LABEL.get(r['family'], r['family']):<14} & "
            f"{r['m']:,} & {r['mu_over_n']:.3f} & {cut*100:.0f}\\% & "
            f"{r['t_allroots']:.4f} & {r['t_transversal']:.4f} & "
            f"{r['t_adaptive']:.4f} & {rel:.2f}$\\times$ \\\\ \\hline".replace(",", "\\,"))
    out.append(r"""\end{tabular}
\caption{Exact-mode runtime at $n=1600$: one instance per family, best of five
runs, one core of an Intel Xeon Gold 6248, Python 3.12. ``Root cut'' is
$1-|S|/n$. The final column is the adaptive variant against whichever
\emph{fixed} strategy is better on that family, so a value near $1$ means the
switch chose correctly. Because each row is a single instance, differences
within a few percent of $1$ should be read as ties.}
\label{tab:runtime}
\end{table}""")
    return "\n".join(out)


# ----------------------------------------------------------------- ablation
def table_ablation(d, n_target=1600):
    # Median over the draws, not whichever row happens to come last.
    # table_ablation_time medians the same draws and the text reads the two
    # tables against each other, so taking one instance here would silently
    # compare a single draw against the median of eight.
    by_var = defaultdict(lambda: defaultdict(list))
    for r in d["rows"]:
        if r.get("n") == n_target and "t" in r and r.get("settled") is not None:
            by_var[r["variant"]][r["family"]].append(r["settled"])
    fams = ["near_tree", "sparse_er", "grid", "dense_er"]
    out = [prov_comment(d, "ablation.json")]
    out.append(r"""\begin{table}[ht]
\centering
\small
\begin{tabular}{|l|l|r|r|r|r|}
\hline
 & \textbf{acceleration added} & \multicolumn{4}{c|}{\textbf{settled vertices}} \\ \cline{3-6}
 & & near tree & sparse ER & grid & dense ER \\ \hline""")
    for v in ["A0", "A1", "A2", "A3", "A4", "A5", "A6", "A7"]:
        if v not in by_var:
            continue
        label = ABLATION_TEX[v]
        cells = []
        for f in fams:
            xs = by_var[v].get(f)
            cells.append(f"{round(st.median(xs)):,}".replace(",", "\\,")
                         if xs else "---")
        out.append(f"{v} & {label} & " + " & ".join(cells) + r" \\ \hline")
    out.append(r"""\end{tabular}
\caption{Ablation at $n=1600$: settled vertices (equivalently $\arg\min$
operations) as each acceleration is switched on, cumulatively, median over the
same draws as Table~\ref{tab:ablation_time}. A0 disables the
truncation entirely; A1 and A5 are the ``all roots'' and ``transversal''
configurations of Table~\ref{tab:runtime}. A dash marks a configuration not
run (A0 is capped by edge count). Every rung returns the same girth on every
instance.}
\label{tab:ablation}
\end{table}""")
    return "\n".join(out)


def table_ablation_time(d, n_target=1600):
    """Wall clock per rung -- the ablation chain as a timing result, so the
    practical claim does not rest on the edge-removal comparison alone."""
    by = defaultdict(lambda: defaultdict(list))
    for r in d["rows"]:
        if r.get("n") == n_target and "t" in r:
            by[r["variant"]][r["family"]].append(r["t"] * 1e3)
    fams = ["near_tree", "sparse_er", "grid", "small_world", "geometric", "dense_er"]
    fams = [f for f in fams if any(f in by[v] for v in by)]
    out = [prov_comment(d, "ablation.json")]
    out.append(r"""\begin{table}[ht]
\centering
\small
\begin{tabular}{|l|l|""" + "r|" * len(fams) + r"""}
\hline
 & \textbf{acceleration added} & \multicolumn{""" + str(len(fams)) +
        r"""}{c|}{\textbf{median wall clock (ms)}} \\ \cline{3-""" + str(2 + len(fams)) + r"""}
 & & """ + " & ".join(FAMILY_LABEL.get(f, f) for f in fams) + r""" \\ \hline""")
    for v in ["A0", "A1", "A2", "A3", "A4", "A5", "A6", "A7"]:
        if v not in by:
            continue
        cells = []
        for f in fams:
            xs = by[v].get(f)
            cells.append(f"{st.median(xs):,.1f}".replace(",", "\\,") if xs else "---")
        out.append(f"{v} & {ABLATION_TEX[v]} & " + " & ".join(cells) + r" \\ \hline")
    out.append(r"""\end{tabular}
\caption{The ablation of Table~\ref{tab:ablation} as wall clock rather than
operation counts, at $n=""" + f"{n_target}" + r"""$, median over the same draws.
A1 is the $n$-root baseline with truncation and A7 the configuration we
recommend; reading down a column shows what each acceleration is worth in time
on that family, which is the comparison the edge-removal figure of
Section~\ref{subsec:exp_runtime} does not make. A dash marks a configuration
not run.}
\label{tab:ablation_time}
\end{table}""")
    return "\n".join(out)


# ----------------------------------------------------------------- frontier
def table_frontier(d):
    by_pair = defaultdict(list)
    for r in d["rows"]:
        by_pair[(r["alpha"], r["beta"])].append(r)
    out = [prov_comment(d, "frontier.json")]
    out.append(r"""\begin{table}[ht]
\centering
\small
\begin{tabular}{|r|r|r|r|r|r|r|}
\hline
$\alpha$ & $\beta$ & $\kappa(\alpha,\beta)$ & \textbf{max ratio} & \textbf{mean ratio} & \textbf{deletions} & \textbf{work} \\ \hline""")
    for (a, b) in sorted(by_pair):
        rs = by_pair[(a, b)]
        kap = rs[0]["kappa"]
        mx = max(r["ratio"] for r in rs)
        mn = st.mean(r["ratio"] for r in rs)
        dels = sum(r["deletions"] for r in rs)
        work = st.mean(r["work_frac"] for r in rs if r.get("work_frac"))
        kaps = "$\\infty$" if kap == float("inf") else f"{kap:.2f}"
        out.append(f"{a:.2f} & {b:.2f} & {kaps} & {mx:.4f} & {mn:.4f} & "
                   f"{dels} & {work:.3f} \\\\ \\hline")
    # Derive every quantity quoted in the caption from the data, so a rerun
    # cannot leave the prose asserting something the table no longer shows.
    n_inst = max(len(v) for v in by_pair.values())
    worst_ratio = max(r["ratio"] for r in d["rows"])
    wf = [r["work_frac"] for r in d["rows"] if r.get("work_frac")]
    max_saved = (1 - min(wf)) * 100 if wf else 0.0
    ratio_clause = (
        r"the ratio is exactly $1$, not merely below $\kappa(\alpha,\beta)$"
        if worst_ratio <= 1 + 1e-9 else
        f"the worst ratio observed was ${worst_ratio:.4f}$, far below "
        r"$\kappa(\alpha,\beta)$")
    out.append(r"""\end{tabular}
\caption{Approximate mode on the multiscale family, $""" + str(n_inst) +
        r"""$ instances per
parameter pair. ``max ratio'' and ``mean ratio'' are $\widehat\gamma/\gamma^*$
over all instances; ``deletions'' is the total number of vertices the discard
rule removed across those instances; ``work'' is mean settled vertices relative
to exact mode on the same instance. The returned cycle was a minimum weight
cycle in every run at every pair --- """ + ratio_clause +
        r""" --- and no instance saved more than $""" + f"{max_saved:.1f}" +
        r"""\%$ of the settled vertices.}
\label{tab:frontier}
\end{table}""")
    return "\n".join(out)


# --------------------------------------------------------------------- real
def table_real(rows, prov_files, provs):
    rows = [r for r in rows if "t_allroots" in r]
    rows.sort(key=lambda r: r["n"])
    shas = sorted({p.get("git_sha", "?")[:12] for p in provs})
    dirt = sorted({str(p.get("git_dirty")) for p in provs})
    jobs = sorted({str(p.get("slurm_job_id")) for p in provs})
    cpus = sorted({p.get("cpu", "?") for p in provs})
    out = ["% generated by make_tables.py from " + ", ".join(prov_files),
           f"% git {','.join(shas)} dirty={','.join(dirt)}",
           f"% jobs {','.join(jobs)}",
           f"% cpu {'; '.join(cpus)}"]
    out.append(r"""\begin{table}[ht]
\centering
\small
\begin{tabular}{|l|r|r|r|r|r|r|r|}
\hline
\textbf{Network} & $n$ & $m$ & $\mu/n$ & \textbf{girth} & \textbf{all roots (s)} & \textbf{transversal (s)} & \textbf{adaptive (s)} \\ \hline""")
    for r in rows:
        g = f"{r['girth']:.4g}" if r.get("girth") is not None else "---"
        name = r["name"].replace("_", "\\_")
        out.append(
            f"\\texttt{{{name}}} & {r['n']:,} & {r['m']:,} & {r['mu_over_n']:.3f} & {g} & "
            f"{r['t_allroots']:.3f} & {r['t_transversal']:.3f} & "
            f"{r['t_adaptive']:.3f} \\\\ \\hline".replace(",", "\\,"))
    out.append(r"""\end{tabular}
\caption{Real-world networks. All three exact configurations return the same
girth on every network, and each returned cycle was reconstructed and
re-weighted independently. Weight semantics and provenance for each network
are given in Section~\ref{subsec:artifact}.}
\label{tab:real}
\end{table}""")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)

    jobs = [("timing.json", table_runtime, "table_runtime.tex"),
            ("ablation.json", table_ablation, "table_ablation.tex"),
            ("ablation.json", table_ablation_time, "table_ablation_time.tex"),
            ("frontier.json", table_frontier, "table_frontier.tex")]
    for fname, fn, outname in jobs:
        d = load(args.results, fname)
        if d is None:
            print(f"[skip] {fname} not present")
            continue
        with open(os.path.join(args.out, outname), "w") as f:
            f.write(fn(d) + "\n")
        print(f"[wrote] {outname}")

    # real networks arrive as one JSON per network
    rows, files, provs = [], [], []
    for fn in sorted(os.listdir(args.results)):
        if fn.startswith("real_") and fn.endswith(".json"):
            d = json.load(open(os.path.join(args.results, fn)))
            rows.extend(d["rows"])
            files.append(fn)
            provs.append(d.get("provenance", {}))
    if rows:
        with open(os.path.join(args.out, "table_real.tex"), "w") as f:
            f.write(table_real(rows, files, provs) + "\n")
        print(f"[wrote] table_real.tex ({len(rows)} networks)")


if __name__ == "__main__":
    main()
